[package]
name = "media_player"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31"
cpal = "0.15.3"
av-format = "0.7.1"
av-codec = "0.3.1"
mp3-duration = "0.1.10"
kalosm-sound = "0.4.0"
futures-util = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }